/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iu;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author peraza
 */
public class VentanaPrincipalCombo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipalCombo
     */
    private ArrayList<Dialogo> dialogos = new ArrayList();
    
    private int contador = 0;
    
    public VentanaPrincipalCombo() {
        initComponents();
        setLocationRelativeTo(null); //centra al medio del monitor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoDialogo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        comboVentanas = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        nuevoDialogo = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnNuevoDialogo.setText("Nuevo Dialogo");
        btnNuevoDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoDialogoActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        comboVentanas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboVentanasItemStateChanged(evt);
            }
        });
        comboVentanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVentanasActionPerformed(evt);
            }
        });

        menu1.setText("Nuevo");

        nuevoDialogo.setText("Dialogo");
        nuevoDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoDialogoActionPerformed(evt);
            }
        });
        menu1.add(nuevoDialogo);

        jMenuBar1.add(menu1);

        menu2.setText("Aplicacion");

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        menu2.add(salir);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btnNuevoDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(comboVentanas, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(comboVentanas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        setBounds(0, 0, 1073, 434);
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoDialogoActionPerformed
        nuevoDialogo();
    }//GEN-LAST:event_nuevoDialogoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       salir();
    }//GEN-LAST:event_salirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       salir();
    }//GEN-LAST:event_formWindowClosing

    private void btnNuevoDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoDialogoActionPerformed
       nuevoDialogo();
    }//GEN-LAST:event_btnNuevoDialogoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       cerrarSeleccionado();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void comboVentanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVentanasActionPerformed
        //mostrarDialogos();
    }//GEN-LAST:event_comboVentanasActionPerformed

    private void comboVentanasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboVentanasItemStateChanged
                activarDialogo();

    }//GEN-LAST:event_comboVentanasItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnNuevoDialogo;
    private javax.swing.JComboBox comboVentanas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuItem nuevoDialogo;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables

    private void salir() {
       int opcion = JOptionPane.showConfirmDialog(this, "Confirmar salida");
        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0); // termina la ejecución de la JVM
        }
    }

    private void nuevoDialogo() {
        Dialogo d = new Dialogo(this, true,"DIALOGO "+ contador);
        contador++;
        d.setVisible(true);
        dialogos.add(d);
        mostrarDialogos();
        
    }

    public void mostrarDialogos() {
       comboVentanas.removeAllItems();
       for(Dialogo d: dialogos){
           comboVentanas.addItem(d);
       }
       
    }

    private void activarDialogo() {
        Dialogo d = (Dialogo)comboVentanas.getSelectedItem();
        if (d!=null) d.toFront();
    }

    public void cierre(Dialogo unDialogo) {
        dialogos.remove(unDialogo);
        mostrarDialogos();
    }

    private void cerrarSeleccionado() {
        Dialogo d = (Dialogo)comboVentanas.getSelectedItem();
        
        if (d!=null) {
            d.dispose(); //que se termine
            cierre(d);
        }
        
    }
}
