/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorConectados;
import controlador.VistaConectados;
import java.util.ArrayList;
import modelo.Acceso;
import modelo.Administrador;


/**
 *
 * @author peraza
 */
public class DialogoConectados extends javax.swing.JDialog implements VistaConectados{

    private ControladorConectados controlador;
        
    public DialogoConectados(java.awt.Frame parent, boolean modal, Administrador admin) {
        super(parent, modal);
        initComponents();
        controlador=new ControladorConectados(this,admin);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaConectados = new javax.swing.JList();
        bTipoContacto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setViewportView(listaConectados);

        bTipoContacto.setText("Crear Tipo Contacto");
        bTipoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTipoContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bTipoContacto)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTipoContacto)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        setBounds(0, 0, 515, 328);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        controlador.cerrar();

    }//GEN-LAST:event_formWindowClosing

    private void bTipoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTipoContactoActionPerformed
        controlador.CUCrearTipoContacto();
    }//GEN-LAST:event_bTipoContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTipoContacto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaConectados;
    // End of variables declaration//GEN-END:variables

    @Override    
    public void mostrarConectados(ArrayList<Acceso> conectados) {
      listaConectados.setListData(conectados.toArray());
    }
    
    @Override
    
    public void mostrarAdmin(String nombre){
      setTitle("USUARIO: "+nombre.toUpperCase());

    }
    
   @Override
   
   public void ejecutarCUCrearTipoContacto(){
       new DialogoCrearTipoContacto(this, false).setVisible(true);
   }
}
