/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorAgenda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Agenda;
import modelo.Contacto;
import modelo.Telefono;
import modelo.TipoContacto;
import modelo.UsuarioAgenda;
import utilidades.Observable;
import utilidades.Observador;

/**
 *
 * @author saul
 */
public class DialogoBusqueda extends javax.swing.JDialog {

    private ControladorAgenda controlador;
    ArrayList<Contacto> listaContactos;
    /**
     * Creates new form DialogoBusqueda
     */
    public DialogoBusqueda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
    }

    public void setControlador(ControladorAgenda controlador) {
        this.controlador = controlador;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaResultado = new javax.swing.JList();
        lblDetalles = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Telefono");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        listaResultado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaResultadoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetalles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblDetalles)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        setBounds(0, 0, 534, 381);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void listaResultadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaResultadoValueChanged
        // TODO add your handling code here:
        verDetalles();

    }//GEN-LAST:event_listaResultadoValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetalles;
    private javax.swing.JList listaResultado;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables

    public void buscar() {
        if(controlador!=null) controlador.buscar(tfTelefono.getText());



        
    }

    private void verDetalles() {
        int pos = listaResultado.getSelectedIndex();
        if (pos==-1) {
            lblDetalles.setText("Detalles: no hay detalles.");
            return;
        }
        
        Contacto c = listaContactos.get(pos);
        
        controlador.detalles(c);
          
        
    }

    private String formatear(Contacto c) {
       return c.getNombre()+" ("+c.getTelefono().getNumero()+" ).";
    }
    

    public void mostrarResultadoBusqueda(ArrayList<Contacto> lista) {
        this.listaContactos=lista;
        ArrayList<String> listado = new ArrayList(); 
        for (Contacto c : listaContactos) {
            listado.add(formatear(c));
        }
            listaResultado.setListData(listado.toArray());
    }

    public void mostrarDetalles(Date fechaCreacion, String nombre, TipoContacto tipoContacto, Telefono telefono) {
        String fecha = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss").format(fechaCreacion);
        lblDetalles.setText("Detalles: "+nombre+" - "+tipoContacto.getNombre()+" - "+  telefono.getNumero()+" - "+fecha);            


    }
    
}
