/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistaEscritorio;

import controlador.ControladorAgenda;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Acceso;
import modelo.Agenda;
import modelo.AgendaException;
import modelo.Contacto;
import modelo.Modelo;
import modelo.Telefono;
import modelo.TipoContacto;
import modelo.TipoTelefono;
import modelo.UsuarioAgenda;
import controlador.VistaAgenda;
import java.awt.Frame;




/**
 *
 * @author peraza
 */
public class DialogoAgenda extends javax.swing.JDialog implements VistaAgenda{
    private ControladorAgenda controlador;
    private DialogoBusqueda dialogoB;

    /**
     * Creates new form DialogoCrearContacto
     */
   
    public DialogoAgenda(java.awt.Frame parent, boolean modal, Acceso a) {
        super(parent, modal);
        initComponents();
        dialogoB = new DialogoBusqueda(parent, false);
        controlador = new ControladorAgenda(this,a);
        dialogoB.setControlador(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboTipoContacto = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCrearContacto = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listContactos = new javax.swing.JList();
        btnBuscar = new javax.swing.JButton();
        comboTipoTelefono = new javax.swing.JComboBox();
        lblTelefono = new javax.swing.JLabel();
        bEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CREAR CONTACTO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        comboTipoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoContactoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo Contacto:");

        jLabel2.setText("Nombre");

        jLabel3.setText("Teléfono");

        btnCrearContacto.setText("Crear contacto");
        btnCrearContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContactoActionPerformed(evt);
            }
        });

        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        jLabel4.setText("CONTACTOS");

        jScrollPane1.setViewportView(listContactos);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        comboTipoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoTelefonoActionPerformed(evt);
            }
        });

        lblTelefono.setText("Tipo Telefono:");

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(136, 136, 136))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(comboTipoTelefono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboTipoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCrearContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bEditar)
                        .addGap(38, 38, 38)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnCrearContacto)
                    .addComponent(bEditar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoContactoActionPerformed

    private void btnCrearContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContactoActionPerformed
        crearContacto();
    }//GEN-LAST:event_btnCrearContactoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        controlador.nuevoDialogo();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logout();
       
    }//GEN-LAST:event_formWindowClosing

    private void comboTipoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoTelefonoActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        editar();
    }//GEN-LAST:event_bEditarActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearContacto;
    private javax.swing.JComboBox comboTipoContacto;
    private javax.swing.JComboBox comboTipoTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JList listContactos;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables



    private void crearContacto() {
        String nom = tfNombre.getText();
        String tel = tfTelefono.getText();
        TipoContacto tc = (TipoContacto)comboTipoContacto.getSelectedItem();
        TipoTelefono tf = (TipoTelefono)comboTipoTelefono.getSelectedItem();
        
        controlador.crearContacto(nom,tel,tc,tf); 
    }





    private void logout() {
        controlador.logout();

    }
    
    @Override
    public void buscar(){
        dialogoB.setVisible(true);
    }
    

    @Override
    
    public void mostrarTiposContacto(ArrayList<TipoContacto> tiposContacto) {
        comboTipoContacto.removeAllItems();
        for(TipoContacto tc : tiposContacto){
            comboTipoContacto.addItem(tc);
        }
    }
    
    @Override
    public void mostrarTiposTelefono(ArrayList<TipoTelefono> tiposTelefono) {
        comboTipoTelefono.removeAllItems();
        for(TipoTelefono tt : tiposTelefono){
            comboTipoTelefono.addItem(tt);
        }
    }
    
    private void setearTitulo(UsuarioAgenda u) {
        setTitle(u.getNombreCompleto().toUpperCase()+" - Contactos: "+u.getAgenda().cantidadContactos());

    }
    
    @Override
    
    public void mostrarEstado(UsuarioAgenda u) {
        limpiarCampos();
        setearTitulo(u);
        listContactos.setListData(u.getAgenda().getContactos().toArray());
        dialogoB.setTitle("Busqueda en la agenda de "+u.getNombreCompleto());
        dialogoB.buscar();
    }    
    
    @Override
    
    public void mostrarMensaje(String msg){
            JOptionPane.showMessageDialog(this, msg);
    
    }
    


    @Override
    public void mostrarResultadoBusqueda(ArrayList<Contacto> lista) {
        dialogoB.mostrarResultadoBusqueda(lista);
    }

    @Override
    public void mostrarDetalles(Date fechaCreacion, String nombre, TipoContacto tipoContacto, Telefono telefono) {
       dialogoB.mostrarDetalles(fechaCreacion,nombre,tipoContacto,telefono);
    }

    private void editar() {
        Contacto c = (Contacto)listContactos.getSelectedValue();
        if(c!=null) new DialogoModificarContacto((Frame)getParent(), true, c).setVisible(true);
    }

    private void limpiarCampos() {
        tfNombre.setText("");
        tfTelefono.setText("");
    }




}
